### ISSUE TITLE
Generate and publish documentation site for each commit to master

### ISSUE THREAD

**Issue by rastersize** [spotify/HubFramework#27]
We need to generate and then publish our documentation for each commit to master.

### Tasks
- [ ] Fix master branch check in Travis-CI config.
- [ ] Set the `DOCS_BUILD_NUMBER` in Travis-CI environment.
- [ ] Add a deployment SSH key and encrypt the passphrase for Travis integration. 
- [ ] Merge the two Xcode 8 jobs.

**Comment by rastersize** [comment]
Moved to be a project instead; “[Automatic documentation](https://github.com/spotify/HubFramework/projects/2)”.
